import DashboardWrappper from "./dashboardWrapper";
import "./globals.css";
import { Roboto } from "next/font/google";
import { options } from "./api/auth/[...nextauth]/options";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { Toaster } from "react-hot-toast";
const roboto = Roboto({
  weight: ["400", "300", "100"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <SessionProviderWrapper>
          <DashboardWrappper>
            <Toaster />
            {children}
          </DashboardWrappper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
